[package]
name = "collision_engine"
version = "1.0.1"
edition = "2021"

[dependencies]
rand = "0.9.2"
tokio = { version = "1.36", features = ["full"] }
tokio-tungstenite = "0.20"
futures-util = "0.3"
wide = "1.1.1"
